### PR TITLE
Change CHART.JS dependency to version 4

### LINKED ISSUE #76: chartjs-adapter-luxon 1.2.0 is incompatible with chart.js 4.x
I'm seeing the following error when I attempt to update to chart.js 4.x, released ~5 hours ago:

```
D:\GitHub\chart>npm install chart.js@latest chartjs-adapter-luxon@latest
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: stl-status-chart@1.0.0
npm ERR! Found: chart.js@4.0.1
npm ERR! node_modules/chart.js
npm ERR!   chart.js@"4.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer chart.js@"^3.0.0" from chartjs-adapter-luxon@1.2.0
npm ERR! node_modules/chartjs-adapter-luxon
npm ERR!   chartjs-adapter-luxon@"1.2.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

This is similar to #61 which happened when luxon updated its major version.

### PR DESCRIPTION
**Pull request by stockiNail**
Fix #76

### CODE REVIEW

**Comment by benmccann** [comment]
`peerDependencies` needs to be updated to fix the error. You could change it to `>=3.0.0` in order to support both Chart.js 3 and 4

**Comment by stockiNail** [comment]
> `peerDependencies` needs to be updated to fix the error. You could change it to `>=3.0.0` in order to support both Chart.js 3 and 4

Thank you @benmccann ! Done!

**Review by benmccann — APPROVED** [review]

**Review by kurkle — APPROVED** [review]

**Comment by benmccann** [comment]
Thanks for taking a look @kurkle! I don't have the ability to merge on this repo. Would you be able to merge it and cut a new release?

**Comment by nook24** [comment]
This breaks dependencies for all who are using `"chartjs-adapter-luxon": "^1.2.0"` in their package.json. npm will install `chartjs-adapter-luxon` in version 1.2.1 which depends on Chartjs 4 which is a breaking change.

Could you please release chartjs-adapter-luxon 1.2.2 which will depend on Chartjs 3.x again to fix this? Took me a while to find this.

// Edit
I guess the change from `"chart.js": "^3.0.0",` to `"chart.js": ">=3.0.0",` is is why my npm install installs Chartjs 4

**Comment by kurkle** [comment]
> // Edit I guess the change from `"chart.js": "^3.0.0",` to `"chart.js": ">=3.0.0",` is is why my npm install installs Chartjs 4

Do you have `chart.js` as dependency at all? it should not install v4 if you have v3 already.

**Pull request merged**
