### PR TITLE
chore: update packaging to match main chart.js library

### LINKED ISSUE #78: Import issue with chartjs-adapter-luxon 1.2.1
After upgrading to chartjs-adapter-luxon@1.2.1 (and chart.js@4.0.1), I get the following error:

`Error: Failed to resolve entry for package "chart.js". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." entry in "chart.js" package`

Edit: upon a bit more digging, it seems to only throw this error when running server-side (eg, SSR). No error when run client-side.

### PR DESCRIPTION
**Pull request by benmccann**
closes https://github.com/chartjs/chartjs-adapter-luxon/issues/78

### CODE REVIEW

**Comment by kurkle** [comment]
Karma needs the umd one, need to change that. I guess the unminified one would be better there, but as these are so simple libs, I guess it does not really matter.

**Comment by benmccann** [comment]
looks like this will need a couple more tweaks. I sent https://github.com/chartjs/chartjs-adapter-luxon/pull/80 as a start and will come back to this afterwards

**Comment by benmccann** [comment]
This is passing the CI and ready for review now

**Review by kurkle — APPROVED** [review]

**Comment by benmccann** [comment]
Thanks @kurkle! Any chance we could get a new release?

**Comment by benmccann** [comment]
@kurkle just checking in to see if we can get a new release. thanks!

**Pull request merged**
