### PR TITLE
Change dependencies of Luxon versions

### LINKED ISSUE #61: chartjs-adapter-luxon 1.1.0 is incompatible with luxon 3.0.1
I'm seeing the following npm warning when I attempt to update to today's release of luxon 3.0.1:

```
D:\GitHub\chart>npm install luxon@latest
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: stl-status-chart@1.0.0
npm WARN Found: luxon@2.5.0
npm WARN node_modules/luxon
npm WARN   peer luxon@"^1.0.0 || ^2.0.0" from chartjs-adapter-luxon@1.1.0
npm WARN   node_modules/chartjs-adapter-luxon
npm WARN     chartjs-adapter-luxon@"^1.1.0" from the root project
npm WARN   1 more (the root project)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer luxon@"^1.0.0 || ^2.0.0" from chartjs-adapter-luxon@1.1.0
npm WARN node_modules/chartjs-adapter-luxon
npm WARN   chartjs-adapter-luxon@"^1.1.0" from the root project

changed 1 package, and audited 81 packages in 457ms

10 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

This may be related to:

https://github.com/chartjs/chartjs-adapter-luxon/blob/1b1c23073eb364bd5bd25de6161a19be44d5b5fc/package.json#L56

It appears that chartjs-adapter-luxon needs to be updated to accept the luxon 3.x series.

(Thanks again for your great work! I use it in the [microsoft/STL Status Chart](https://microsoft.github.io/STL/). :smile_cat:)

### PR DESCRIPTION
**Pull request by stockiNail**
Fix #61

### CODE REVIEW

**Comment by stockiNail** [comment]
@benmccann @kurkle I'd like to spend time to increase the test cases in order to test all methods of the interface to be sure that to every new Luxon version the adapter will continue working. What do you think?

**Comment by kurkle** [comment]
> @benmccann @kurkle I'd like to spend time to increase the test cases in order to test all methods of the interface to be sure that to every new Luxon version the adapter will continue working. What do you think?

Sounds good!

**Comment by stockiNail** [comment]
Converted in draft in order to change also the package-lock.json  with last modules (for instance Chart,js 3.8.0)

**Comment by stockiNail** [comment]
Applied last versions of dependencies.

**Review by benmccann — APPROVED** [review]

**Review by kurkle — APPROVED** [review]

**Pull request merged**
